spring:
  application:
    name: dynamic-simulation-server

  cloud:
    function:
      definition: consumeRun
    stream:
      bindings:
        consumeRun-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.run
          group: dsGroup
          consumer:
            concurrency: 2
        publishResult-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.result
        publishRun-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.run
      output-bindings: publishResult;publishRun

network-store-server:
  preloading-strategy: COLLECTION

powsybl-ws:
  database:
    name: ds
