spring:
  application:
    name: dynamic-simulation-server

  cloud:
    function:
      definition: consumeRun;consumeCancel
    stream:
      bindings:
        consumeRun-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.run
          group: dsGroup
          consumer:
            concurrency: 2
        publishRun-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.run
        publishResult-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.result
        consumeCancel-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.cancel
        publishCancel-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.cancel
        publishStopped-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.stopped
        publishFailed-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}ds.failed
      output-bindings: publishRun-out-0;publishResult-out-0;publishCancel-out-0;publishStopped-out-0;publishFailed-out-0

powsybl:
  services:
    network-store-server:
      preloading-strategy: COLLECTION

powsybl-ws:
  database:
    name: ds

# default values for dynamic simulation providers is "DynaWaltz"
dynamic-simulation:
  default-provider: DynaWaltz
