server:
  port: 5032

spring:
  rabbitmq:
    addresses: localhost
    port: 5672

powsybl-ws:
  database:
    host: localhost

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080/

gridsuite:
  services:
    timeseries-server:
      base-uri: http://localhost:5037
    dynamic-mapping-server:
      base-uri: http://localhost:5036

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
