server:
  port: 5032

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080/

gridsuite:
  services:
    timeseries-server:
      base-uri: http://localhost:5037
    dynamic-mapping-server:
      base-uri: http://localhost:5036
    report-server:
      base-uri: http://localhost:5028
