server:
  port: 5032

spring:
  rabbitmq:
    addresses: localhost
    port: 5672

powsybl-ws:
  database:
    host: localhost

network-store-server:
  base-uri: http://localhost:8080/

timeseries-server:
  base-uri: http://localhost:5101

dynamic-mapping-server:
    base-uri: http://localhost:5036
